[project]
name = "rag"
version = "0.1.0"
description = "A simple RAG service."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "sentence-transformers>=5.2.3",
    "ucall>=0.5.4",
    "usearch>=2.23.0",
]

[tool.pyright]
venvPath = "."
venv = ".venv"
